Repository hadren-cloud/oxygen-cs-grp2-eq5, pull requests merged in 2023-07, with the labels that each got.

#7 Add kunbernetes manifest files
  Dockerfile
  kubernetes/oxygen/configmap.yaml
  kubernetes/oxygen/deployment.yaml
  kubernetes/oxygen/service.yaml
Labels: enhancement, configuration

#8 Update pipeline for kubernetes deployment
  .github/workflows/build.yaml
Labels: feature, configuration

#10 Create table for hvac actions
  src/main.py
Labels: feature
